### ISSUE TITLE
02 июля

### ISSUE THREAD

**Issue by JAkutenshi** [Pavel-by/paa8382trio1#2]
- [x] не работает сборка с Gradle
- [x] описать функционал чтения графа из файла и случайной генерации графа

**Comment by Pavel-by** [comment]
Ошибка сборки поправлена в [d781235](https://github.com/Pavel-by/paa8382trio1/commit/d7812357ba1872e73c2261ea2c4193e0c5955af4)

**Comment by Pavel-by** [comment]
Добавлено описание генерации & чтения из файла в a0a45ee
