### ISSUE TITLE
Неправильный результат в работе алгоритма (B,C,A; B-A=10, C-A = 12)

### ISSUE THREAD

**Issue by Pavel-by** [Pavel-by/paa8382trio1#9]
Если создать 3 вершины B, C и A и 2 ребра B-A=10 и C-A=12, то алгоритм найдет остовное дерево за 2 шага, хотя правильный ответ 1

**Comment by ahimasyd** [comment]
Точно?
Вот я задал граф
![image](https://user-images.githubusercontent.com/42896832/86536518-eca6bc00-bef0-11ea-83ef-e8a8f9fe6cfa.png)


В конце функции.

Ребро B-A step 0
![image](https://user-images.githubusercontent.com/42896832/86536563-54f59d80-bef1-11ea-8a83-bbedc789e8c0.png)

Ребро  C-A step 0
![image](https://user-images.githubusercontent.com/42896832/86536556-48714500-bef1-11ea-9a58-716351bfd790.png)

**Comment by ahimasyd** [comment]
Ну я щас еще один зуб дам, что все нормально

**Comment by Pavel-by** [comment]
Зуб то не потеряешь?
Важен порядок вершин: сначала добавляется B, потом C, потом A. Важен ли порядок ребер хз, но тоже соблюдай

**Comment by ahimasyd** [comment]
Вот так?
![image](https://user-images.githubusercontent.com/42896832/86536719-8753ca80-bef2-11ea-8012-1507293d6e5c.png)

**Comment by Pavel-by** [comment]
Да, так

**Comment by Pavel-by** [comment]
Кстати, в комментарии можно вставлять код

```kotlin
myFunction(10, 12)
```

**Comment by ahimasyd** [comment]
Ладно, зуб я отдам

**Comment by ahimasyd** [comment]
Смотрите, я там починил
https://github.com/Pavel-by/paa8382trio1/pull/10
